// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// MidtransHandlerInterface is an autogenerated mock type for the MidtransHandlerInterface type
type MidtransHandlerInterface struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields:
func (_m *MidtransHandlerInterface) CreateTransaction() echo.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// VerifyPayment provides a mock function with given fields:
func (_m *MidtransHandlerInterface) VerifyPayment() echo.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for VerifyPayment")
	}

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// NewMidtransHandlerInterface creates a new instance of MidtransHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMidtransHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MidtransHandlerInterface {
	mock := &MidtransHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
