// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	collectors "rub_buddy/features/collectors"

	mock "github.com/stretchr/testify/mock"
)

// CollectorDataInterface is an autogenerated mock type for the CollectorDataInterface type
type CollectorDataInterface struct {
	mock.Mock
}

// GetCollectorByEmail provides a mock function with given fields: email
func (_m *CollectorDataInterface) GetCollectorByEmail(email string) (*collectors.Collectors, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetCollectorByEmail")
	}

	var r0 *collectors.Collectors
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*collectors.Collectors, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *collectors.Collectors); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collectors.Collectors)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: email, password
func (_m *CollectorDataInterface) Login(email string, password string) (*collectors.Collectors, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *collectors.Collectors
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*collectors.Collectors, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *collectors.Collectors); ok {
		r0 = rf(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collectors.Collectors)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: collector
func (_m *CollectorDataInterface) Register(collector collectors.Collectors) (*collectors.Collectors, error) {
	ret := _m.Called(collector)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *collectors.Collectors
	var r1 error
	if rf, ok := ret.Get(0).(func(collectors.Collectors) (*collectors.Collectors, error)); ok {
		return rf(collector)
	}
	if rf, ok := ret.Get(0).(func(collectors.Collectors) *collectors.Collectors); ok {
		r0 = rf(collector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collectors.Collectors)
		}
	}

	if rf, ok := ret.Get(1).(func(collectors.Collectors) error); ok {
		r1 = rf(collector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCollector provides a mock function with given fields: collector
func (_m *CollectorDataInterface) UpdateCollector(collector *collectors.CollectorUpdate) error {
	ret := _m.Called(collector)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCollector")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*collectors.CollectorUpdate) error); ok {
		r0 = rf(collector)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCollectorDataInterface creates a new instance of CollectorDataInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCollectorDataInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CollectorDataInterface {
	mock := &CollectorDataInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
